clean:
	rm -rf *.o *.gv *.out
	rm -rf output.s


init:
	./run.sh pattern/init1.c

init2:
	./comp.sh pattern/init1.c

par1:
	./run.sh pattern/par1.c

par2:
	./run.sh pattern/par2.c
par22:
	./comp.sh pattern/par2.c

